name: Lint and Build

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.16.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Run TS
        run: npm run ts

  build:
    # needs: lint
    if: startsWith(github.ref, 'refs/tags/rc-')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 16.16.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # - name: Build app
      #   run: npm run build

      - name: Update ticket with last release
        env:
          TAG_NAME: ${{github.ref_name}},
          OAUTH: ${{secrets.OAUTH}},
          ORG_ID: ${{secrets.ORG_ID}},
          ISSUE_ID: ${{secrets.ISSUE_ID}},
          ACTOR: ${{github.actor}}
        run: node .github/scripts/tracker-ticket.js

      - name: Create docker-image
        env:
          TAG_NAME: ${{github.ref_name}},
        run: node .github/scripts/docker-image.js

      - name: Update ticket comment with docker image
        env:
          TAG_NAME: ${{github.ref_name}},
          OAUTH: ${{secrets.OAUTH}},
          ORG_ID: ${{secrets.ORG_ID}},
          ISSUE_ID: ${{secrets.ISSUE_ID}}
        run: node .github/scripts/docker-comment.js
